/**
 * Curated global scholarships, PhD programs, and fellowships.
 * All data is real, verified, and sourced from official websites.
 * No fake or fabricated data.
 */
import { BaseSource } from './base.js';
import type { RawListing } from '../types.js';

interface CuratedEntry {
  title: string;
  provider: string;
  url: string;
  description: string;
  countries: string[];
  fields: string[];
  degreeLevels: string[];
  fundingKind: 'full' | 'partial' | 'unknown';
  eligibility: string[];
  benefits: string[];
  tags: string[];
  deadline?: string;
}

const SCHOLARSHIPS: CuratedEntry[] = [
  {
    title: 'Fulbright Foreign Student Program',
    provider: 'US Department of State',
    url: 'https://foreign.fulbrightonline.org/',
    description: 'Prestigious US government scholarship for international students to pursue graduate study in the US. Covers full tuition, living stipend, airfare, and health insurance.',
    countries: ['US'],
    fields: ['all'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Citizens of participating countries', "Bachelor's degree required", 'Strong English proficiency'],
    benefits: ['Full tuition coverage', 'Monthly living stipend', 'Airfare allowance', 'Health insurance'],
    tags: ['fully-funded', 'usa', 'prestigious', 'graduate'],
    deadline: 'Varies by country (usually Oct-Nov)',
  },
  {
    title: 'Chevening Scholarships',
    provider: 'UK Foreign Commonwealth & Development Office',
    url: 'https://www.chevening.org/',
    description: 'UK government flagship international scholarship for one-year Masters study at any UK university. Fully funded with tuition, living allowance, and travel.',
    countries: ['GB'],
    fields: ['all'],
    degreeLevels: ['master'],
    fundingKind: 'full',
    eligibility: ['Citizens of Chevening-eligible countries', '2+ years work experience', 'Strong leadership qualities'],
    benefits: ['Full tuition fees', 'Monthly living allowance', 'Return economy airfare', 'Visa application costs'],
    tags: ['fully-funded', 'uk', 'prestigious', 'master'],
    deadline: 'November each year',
  },
  {
    title: 'DAAD Scholarships for Study in Germany',
    provider: 'German Academic Exchange Service (DAAD)',
    url: 'https://www.daad.de/en/',
    description: 'Germany largest scholarship program for international students to study or research at German universities. Monthly stipend, health insurance, and travel allowance.',
    countries: ['DE'],
    fields: ['all'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Varies by program', "Bachelor's degree with strong GPA", 'Language proficiency per program'],
    benefits: ['Monthly stipend EUR 850-1200', 'Health insurance coverage', 'Travel allowance', 'Study allowance'],
    tags: ['fully-funded', 'germany', 'eu', 'graduate'],
    deadline: 'October-November for most programs',
  },
  {
    title: 'Commonwealth Scholarships',
    provider: 'Commonwealth Scholarship Commission (UK)',
    url: 'https://cscuk.fcdo.gov.uk/',
    description: 'For citizens of Commonwealth countries to study Masters or PhD in the UK. Covers tuition, living costs, travel, and thesis grant.',
    countries: ['GB'],
    fields: ['development-related'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Commonwealth citizens', 'Not ordinarily resident in UK', 'Strong academic record'],
    benefits: ['Tuition fees', 'Living allowance', 'Return airfare', 'Thesis grant'],
    tags: ['fully-funded', 'uk', 'commonwealth', 'developing-countries'],
    deadline: 'December each year',
  },
  {
    title: 'Erasmus Mundus Joint Master Degrees',
    provider: 'European Commission',
    url: 'https://erasmus-plus.ec.europa.eu/',
    description: 'EU flagship program for international master degrees delivered by consortia of European universities. Full tuition waiver, monthly grant, and travel allowance.',
    countries: ['EU'],
    fields: ['all'],
    degreeLevels: ['master'],
    fundingKind: 'full',
    eligibility: ['Open to students worldwide', "Bachelor's degree required", 'English proficiency'],
    benefits: ['Tuition waiver', 'Monthly grant EUR 800-1000', 'Travel allowance', 'Insurance coverage'],
    tags: ['fully-funded', 'europe', 'exchange', 'eu'],
    deadline: 'Varies by institution (usually Jan-Mar)',
  },
  {
    title: 'Gates Cambridge Scholarship',
    provider: 'University of Cambridge',
    url: 'https://www.gatescambridge.org/',
    description: 'Full-cost scholarship at University of Cambridge for outstanding international students. Covers all study costs, living allowance, flights, and family allowance.',
    countries: ['GB'],
    fields: ['all'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Non-UK citizens', 'Apply to Cambridge first', 'Exceptional academics and leadership'],
    benefits: ['Full cost of study', 'Living allowance', 'Return airfare', 'Family allowance'],
    tags: ['fully-funded', 'cambridge', 'uk', 'prestigious', 'phd'],
    deadline: 'October-December',
  },
  {
    title: 'Chinese Government Scholarship (CSC)',
    provider: 'China Scholarship Council',
    url: 'https://www.campuschina.org/',
    description: 'Chinese government scholarship for international students to study at Chinese universities. Full tuition, accommodation, living allowance, and medical insurance.',
    countries: ['CN'],
    fields: ['all'],
    degreeLevels: ['bachelor', 'master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Non-Chinese citizens', 'Age limits apply per level', 'Good health'],
    benefits: ['Full tuition', 'Accommodation', 'Monthly living allowance', 'Medical insurance'],
    tags: ['fully-funded', 'china', 'asia', 'all-levels'],
    deadline: 'Varies by university (Feb-April)',
  },
  {
    title: 'MEXT Scholarship (Japan)',
    provider: 'Japanese Ministry of Education',
    url: 'https://www.mext.go.jp/en/',
    description: 'Japanese government scholarship for international students at Japanese universities. Full tuition, monthly stipend, and airfare.',
    countries: ['JP'],
    fields: ['all'],
    degreeLevels: ['bachelor', 'master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Citizens of countries with diplomatic relations with Japan', 'Under 35 years old'],
    benefits: ['Full tuition', 'Monthly stipend JPY 117,000-145,000', 'Round-trip airfare'],
    tags: ['fully-funded', 'japan', 'asia', 'all-levels'],
    deadline: 'May-June each year',
  },
  {
    title: 'Australia Awards Scholarships',
    provider: 'Australian Government (DFAT)',
    url: 'https://www.australiaawards.gov.au/',
    description: 'Australian government scholarship for students from developing countries. Covers full tuition, airfare, living allowance, and establishment allowance.',
    countries: ['AU'],
    fields: ['development-priorities'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Citizens of eligible developing countries', '2+ years work experience', 'Not a permanent resident of Australia'],
    benefits: ['Full tuition', 'Return airfare', 'Living allowance', 'Establishment allowance'],
    tags: ['fully-funded', 'australia', 'developing-countries', 'graduate'],
    deadline: 'Varies by country',
  },
  {
    title: 'Schwarzman Scholars Program',
    provider: 'Schwarzman College, Tsinghua University',
    url: 'https://www.schwarzmanscholars.org/',
    description: 'One-year Masters in Global Affairs at Tsinghua University, Beijing. Highly selective leadership program with full funding.',
    countries: ['CN'],
    fields: ['global-affairs', 'public-policy', 'business'],
    degreeLevels: ['master'],
    fundingKind: 'full',
    eligibility: ['Undergraduate degree', 'Age 18-28', 'All nationalities'],
    benefits: ['Full tuition', 'Room and board', 'Travel costs', 'Personal stipend'],
    tags: ['fully-funded', 'china', 'leadership', 'master', 'prestigious'],
    deadline: 'September each year',
  },
  {
    title: 'Rhodes Scholarship',
    provider: 'Rhodes Trust / University of Oxford',
    url: 'https://www.rhodeshouse.ox.ac.uk/',
    description: 'World oldest international scholarship for postgraduate study at Oxford University. Fully funded with fees, stipend, and travel.',
    countries: ['GB'],
    fields: ['all'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Citizens of eligible countries', 'Age 18-27', 'Strong academics and character'],
    benefits: ['Full Oxford fees', 'Living stipend', 'Return airfare'],
    tags: ['fully-funded', 'oxford', 'uk', 'prestigious', 'fellowship'],
    deadline: 'August-October',
  },
  {
    title: 'Marie Sklodowska-Curie Actions (MSCA) Doctoral Networks',
    provider: 'European Commission',
    url: 'https://marie-sklodowska-curie-actions.ec.europa.eu/',
    description: 'EU fellowship for doctoral and postdoctoral researchers across any field. Living allowance, mobility allowance, and family allowance.',
    countries: ['EU'],
    fields: ['all'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['Any nationality', 'Must not have resided in host country for 12+ months', "Master's degree or equivalent"],
    benefits: ['Living allowance approx. EUR 3,400/month', 'Mobility allowance', 'Family allowance', 'Research costs'],
    tags: ['phd', 'europe', 'eu', 'fully-funded', 'research'],
    deadline: 'April-September (varies by call)',
  },
  {
    title: 'Humboldt Research Fellowship',
    provider: 'Alexander von Humboldt Foundation',
    url: 'https://www.humboldt-foundation.de/',
    description: 'Fellowship for postdoctoral researchers to conduct research in Germany. Generous monthly stipend and research support.',
    countries: ['DE'],
    fields: ['all'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['PhD degree holders', 'Strong publication record', 'Any nationality'],
    benefits: ['Monthly stipend EUR 2,670-3,170', 'Travel allowance', 'Research allowance', 'Family allowance'],
    tags: ['postdoc', 'germany', 'research', 'fully-funded'],
    deadline: 'Open year-round (rolling)',
  },
  {
    title: 'Vanier Canada Graduate Scholarships',
    provider: 'Government of Canada',
    url: 'https://vanier.gc.ca/',
    description: 'Prestigious doctoral scholarship for top PhD candidates at Canadian universities. CAD 50,000 per year for 3 years.',
    countries: ['CA'],
    fields: ['all'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['Nominated by Canadian universities', 'Any nationality', 'Outstanding academic record'],
    benefits: ['CAD 50,000/year for 3 years', 'Research allowance', 'Conference travel'],
    tags: ['phd', 'canada', 'prestigious', 'fully-funded'],
    deadline: 'November each year',
  },
  {
    title: 'NSF Graduate Research Fellowship (GRFP)',
    provider: 'National Science Foundation',
    url: 'https://www.nsfgrfp.org/',
    description: 'Prestigious US fellowship for outstanding STEM graduate students. Three years of support at USD 37,000/year stipend plus education allowance.',
    countries: ['US'],
    fields: ['stem'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['US citizens or permanent residents', 'Early-career graduate students in STEM'],
    benefits: ['USD 37,000/year stipend', 'USD 16,000 cost-of-education allowance', 'Three years of support'],
    tags: ['phd', 'usa', 'nsf', 'stem', 'fully-funded'],
    deadline: 'October each year',
  },
  {
    title: 'ETH Zurich Doctoral Fellowship',
    provider: 'ETH Zurich',
    url: 'https://ethz.ch/en/doctorate.html',
    description: 'PhD positions at one of the world top technical universities. Full salary as doctoral assistant.',
    countries: ['CH'],
    fields: ['engineering', 'computer-science', 'natural-sciences'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ["Master's degree in relevant field", 'High academic achievement'],
    benefits: ['Full salary approx. CHF 4,200/month', 'Social benefits', 'Research facilities'],
    tags: ['phd', 'switzerland', 'engineering', 'stem'],
    deadline: 'Rolling (contact supervisors)',
  },
  {
    title: 'Max Planck Society PhD Positions',
    provider: 'Max Planck Society',
    url: 'https://www.mpg.de/en',
    description: 'PhD and postdoc positions at 86 world-class research institutes in Germany. Full salary and benefits.',
    countries: ['DE'],
    fields: ['natural-sciences', 'biology', 'medicine', 'social-sciences', 'humanities'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ["Master's degree", 'Open to all nationalities'],
    benefits: ['Full salary per TVoD', 'Social benefits', 'Research infrastructure'],
    tags: ['phd', 'postdoc', 'germany', 'research', 'fully-funded'],
    deadline: 'Rolling',
  },
  {
    title: 'EMBO Fellowships',
    provider: 'European Molecular Biology Organization',
    url: 'https://www.embo.org/funding/',
    description: 'Short- and long-term postdoctoral fellowships in life sciences across European laboratories.',
    countries: ['EU'],
    fields: ['life-sciences', 'biology'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['PhD holders in life sciences', 'Strong research record'],
    benefits: ['Salary per host country standards', 'Travel allowance', 'Health insurance', 'Family allowance'],
    tags: ['postdoc', 'europe', 'biology', 'life-sciences'],
    deadline: 'Short-term: rolling. Long-term: February and August',
  },
  {
    title: 'Rotary Peace Fellowship',
    provider: 'Rotary International',
    url: 'https://www.rotary.org/en/our-programs/peace-fellowships',
    description: 'Fully funded Masters or professional certificate for peace and conflict resolution at partner universities worldwide.',
    countries: ['global'],
    fields: ['peace', 'international-relations', 'conflict-resolution'],
    degreeLevels: ['master'],
    fundingKind: 'full',
    eligibility: ['3+ years work experience in peace-related field', 'Demonstrated commitment to peace'],
    benefits: ['Full tuition', 'Living expenses', 'Travel', 'Internship placement'],
    tags: ['fellowship', 'peace', 'global', 'fully-funded', 'master'],
    deadline: 'May each year',
  },
  {
    title: 'AAAS Science & Technology Policy Fellowships',
    provider: 'American Association for the Advancement of Science',
    url: 'https://www.aaas.org/programs/science-technology-policy-fellowships',
    description: 'Places scientists and engineers into federal executive and legislative agencies in Washington DC.',
    countries: ['US'],
    fields: ['stem'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['PhD + 3 years post-degree experience', 'US citizens'],
    benefits: ['Stipend USD 60,000-100,000', 'Health insurance', 'Professional development'],
    tags: ['fellowship', 'policy', 'usa', 'phd', 'stem'],
    deadline: 'November each year',
  },
];

const PhD_PROGRAMS: CuratedEntry[] = [
  {
    title: 'Wellcome Trust PhD Studentship',
    provider: 'Wellcome Trust',
    url: 'https://wellcome.org/',
    description: 'PhD funding across biomedical sciences, global health, and humanities of medicine at UK institutions.',
    countries: ['GB'],
    fields: ['biomedical', 'health-sciences'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ['Any nationality', 'Strong research potential'],
    benefits: ['Full PhD fees', 'Living stipend', 'Research expenses'],
    tags: ['phd', 'uk', 'biomedical', 'health', 'fully-funded'],
    deadline: 'Rolling — contact supervisors directly',
  },
  {
    title: 'University Positions in Europe',
    provider: 'Various European Universities',
    url: 'https://universitypositions.eu/',
    description: 'Academic jobs and funded PhD positions at European universities. Updated daily with new openings.',
    countries: ['EU'],
    fields: ['all'],
    degreeLevels: ['phd'],
    fundingKind: 'full',
    eligibility: ["Master's degree or equivalent", 'Varies by position'],
    benefits: ['Salary per host institution', 'Research facilities', 'Conference travel'],
    tags: ['phd', 'europe', 'academic', 'research'],
    deadline: 'Rolling',
  },
];

const FELLOWSHIPS: CuratedEntry[] = [
  {
    title: 'Open Society Foundations Fellowship',
    provider: 'Open Society Foundations',
    url: 'https://www.opensocietyfoundations.org/',
    description: 'Supports independent work on policy-relevant social challenges by innovative thinkers, practitioners, and academics.',
    countries: ['global'],
    fields: ['law', 'policy', 'human-rights', 'social-justice'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'partial',
    eligibility: ['Open to practitioners, academics, activists', 'Strong project proposal'],
    benefits: ['Stipend', 'Project funds', 'Network access'],
    tags: ['fellowship', 'policy', 'human-rights', 'global'],
    deadline: 'September each year',
  },
  {
    title: 'Atlantic Fellows',
    provider: 'Atlantic Institute',
    url: 'https://www.atlanticfellows.org/',
    description: 'Global network of programs for people working toward fairer, healthier, and more inclusive societies.',
    countries: ['global'],
    fields: ['health', 'brain-science', 'racial-equity', 'ocean'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'full',
    eligibility: ['Mid-career professionals', '7-15 years experience'],
    benefits: ['Full program costs', 'Travel', 'Living expenses', 'Network access'],
    tags: ['fellowship', 'mid-career', 'global', 'fully-funded'],
    deadline: 'Varies by program (usually Nov-Feb)',
  },
  {
    title: 'TED Fellowship',
    provider: 'TED',
    url: 'https://www.ted.com/participate/ted-fellows-program',
    description: 'For early-career innovators and creative pioneers with transformative ideas that can change the world.',
    countries: ['global'],
    fields: ['all'],
    degreeLevels: ['master', 'phd'],
    fundingKind: 'partial',
    eligibility: ['Open globally', 'Demonstrated impact in your field'],
    benefits: ['TED Conference attendance', 'TED community access', 'Coaching and mentoring'],
    tags: ['fellowship', 'innovation', 'global', 'leadership'],
    deadline: 'October each year',
  },
];

export class CuratedSource extends BaseSource {
  readonly name = 'curated';
  readonly displayName = 'Curated Global Programs';
  readonly schedule = '0 0 1 * *';
  readonly origin = 'https://fundmystudy.app';

  async fetch(): Promise<RawListing[]> {
    const all = [...SCHOLARSHIPS, ...PhD_PROGRAMS, ...FELLOWSHIPS];
    const now = Math.floor(Date.now() / 1000);

    return all.map((entry, i) => ({
      externalId: `curated-${i}-${entry.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40)}`,
      url: entry.url,
      title: entry.title,
      provider: entry.provider,
      description: entry.description,
      rawFields: entry.fields,
      rawCountries: entry.countries,
      rawDegreeLevels: entry.degreeLevels as any,
      rawFundingKind: entry.fundingKind,
      rawEligibility: entry.eligibility,
      rawBenefits: entry.benefits,
      rawTags: entry.tags,
    }));
  }
}
